name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-18.04
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: armv7
        distro: ubuntu18.04
        run: docker build . --file Dockerfile --platform linux/arm64 --tag billing-system:$(date +%s)
